CREATE TABLE documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    isFolder BOOLEAN NOT NULL,

    -- Metadata
    createdBy TEXT NOT NULL,
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lastModifiedBy TEXT NOT NULL,
    lastModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDeleted BOOLEAN DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;